#!/usr/bin/env python

import pygame

from menu import Menu
import modes
from render import Render
from controller import Keyboard
from cuts import ShowLogo

def aftris_game(screen, mode):
    background = pygame.image.load('res/ingamegnd.png').convert_alpha()
    screen.blit(background, (0, 0))
    pygame.display.flip()

    if mode == 0:
        tetris = modes.Levels()
    elif mode == 1:
        tetris = modes.Forever()

    user = Keyboard(tetris.game)
    render = Render(tetris)

    while not tetris.game_over:
        user.update()
        tetris.update()

        dirty = [screen.blit(render.update(), (20, 40))]
        dirty.append(screen.blit(render.next, (250, 50)))
        dirty.append(screen.blit(render.score, (250, 10)))
        pygame.display.update(dirty)

        
def main():
    screen = pygame.display.set_mode((640, 480))
    ShowLogo(screen)

    exit_game = False
    while not exit_game:
        menu = Menu(screen, ['Level Mode',
                             'Endless Mode',
                             'Exit'],
                    pygame.image.load('res/menugnd.png'))
        menu.run()
        exit_game = (menu.cancelled or menu.selected == 2)

        if not exit_game:
            aftris_game(screen, mode=menu.selected)
            
if __name__ == '__main__':
    pygame.init()
    main()
